import type { Metadata } from "next";
import snapshotJson from "@/data/mpc.json";
import type { MpcSnapshot } from "@/lib/mpc";
import { CompareTable } from "@/ui/components/compare-table";

export const metadata: Metadata = {
	title: "Compare",
	description:
		"Command Code plans priced side by side against OpenCode Go, from a build-time mpc snapshot.",
};

// The snapshot is committed and regenerated with `bun snapshot:mpc`; the page
// never runs mpc itself (Vercel has no bun and cannot scrape the docs).
const snapshot = snapshotJson as MpcSnapshot;

function formatGeneratedAt(iso: string): string {
	const date = new Date(iso);
	if (Number.isNaN(date.getTime())) return iso;
	const formatted = new Intl.DateTimeFormat("en-US", {
		dateStyle: "medium",
		timeStyle: "short",
		timeZone: "UTC",
	}).format(date);
	return `${formatted} UTC`;
}

export default function ComparePage() {
	return (
		<div>
			<div className="max-w-[var(--prose-max)]">
				<h1>Compare</h1>
				<p className="ink-muted mt-4">
					Model pricing across OpenCode Go and each CommandCode plan,
					generated by <span className="mono">mpc</span> at build
					time. Switch plans, filter, and sort by requests per month,
					cost per request, or ability.
				</p>
			</div>

			<CompareTable snapshot={snapshot} />

			<p className="ink-muted mt-6 text-xs">
				Data as of{" "}
				<time dateTime={snapshot.generatedAt}>
					{formatGeneratedAt(snapshot.generatedAt)}
				</time>
				. Regenerate with <code className="mono">bun snapshot:mpc</code>
				.
			</p>
		</div>
	);
}
