import type { Metadata } from "next";
import snapshotJson from "@/data/mpc.json";
import type { MpcSnapshot } from "@/lib/mpc";
import { CompareTable } from "@/ui/components/compare-table";

export const metadata: Metadata = {
	title: "Compare",
	description:
		"Command Code plans priced side by side against OpenCode Go, from a committed mpc snapshot refreshed live.",
};

// The snapshot is committed and regenerated with `bun snapshot:mpc` (and by the
// scheduled snapshot workflow); the page never runs mpc itself (Vercel has no
// bun and cannot scrape the docs). The client then refreshes from the committed
// file, so a visitor sees the newest data without a redeploy.
const snapshot = snapshotJson as MpcSnapshot;

export default function ComparePage() {
	return (
		<div>
			<div className="max-w-[var(--prose-max)]">
				<h1>Compare</h1>
				<p className="ink-muted mt-4">
					Model pricing across OpenCode Go and each CommandCode plan,
					generated by <span className="mono">mpc</span>. Switch
					plans, filter, and sort by requests per month, cost per
					request, or ability.
				</p>
			</div>

			<CompareTable initialSnapshot={snapshot} />
		</div>
	);
}
